name: Build and Deploy Sphinx

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: actions/checkout@v3
      uses: actions/checkout@v3

    - name: photon-platform/action-deploy-sphinx-gh-pages
      uses: photon-platform/action-deploy-sphinx-gh-pages@v15
      with:
        modules_repo_urls: 'https://github.com/geometor/model.git,https://github.com/geometor/render.git'
        python_version: '3.10'  # Optional, default is '3.x'
